# Aquí levanto el servidor.
# Aquí van juntos la base de datos de estacionamiento y el microservicio ParkingService
services:

  # BD
  mysql-parking:
    image: mysql:8.0
    container_name: db_parking
    environment:
      MYSQL_ROOT_PASSWORD: Delfines1
      MYSQL_DATABASE: sicaeparking
    ports:
      # se usa el puerto 3308 para que no choque con el local 3306 ni el de vehículos 3307.
      - "3308:3306"
    volumes:
      - mysqldata_parking:/var/lib/mysql
      - ./BD/MySQL/sicaeparking.sql:/docker-entrypoint-initdb.d/sicaeparking.sql
    networks:
      - sicae-network-parking

  # Microservicio de estacionamiento.
  parking-service:
    build:
      context: ./parkingservice
      dockerfile: Dockerfile
    container_name: parking_service
    ports:
      # Conexión entre puerto 8085 externo al 8085 interno de la app Spring Boot.
      - "8085:8085"
    depends_on:
      - mysql-parking
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-parking:3306/sicaeparking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Delfines1
    networks:
      - sicae-network-parking

volumes:
  mysqldata_parking:

networks:
  sicae-network-parking:
    driver: bridge