spring.application.name=userservice
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/sicaeUsuario
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.configuration.map-underscore-to-camel-case=true