spring.application.name=parkingservice

# Configuramos el puerto 8084 para no chocar con los otros servicios
server.port=8085

# Configuraci\u00c3\u00b3n de la base de datos MySQL (Local para pruebas en NetBeans)
spring.datasource.url=jdbc:mysql://localhost:3306/sicaeparking
spring.datasource.username=root
spring.datasource.password=Delfines1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
